name: Docker Image CI

on:
  push:
    branches: [ "testing-docker-image" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Build the Docker image
      run: docker build -t my-portfolio-image .

    - name: Show Docker image details
      run: docker images

    - name: Start services with docker-compose
      run: docker-compose up -d
      
    - name: Wait for application to start
      run: sleep 10 # Puedes ajustar el tiempo de espera según tus necesidades

    